// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATahcrXQ7uqmcwBNk0QkQmrL-23AVSdG4',
    appId: '1:949650895557:web:a83ae6b59e6a3d8bdeb6ac',
    messagingSenderId: '949650895557',
    projectId: 'fir-cli-demo-6be41',
    authDomain: 'fir-cli-demo-6be41.firebaseapp.com',
    storageBucket: 'fir-cli-demo-6be41.appspot.com',
    measurementId: 'G-BPNTWV016Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClPCWp2vftoW3tRfKqqT6sYNwT2nVxhJ8',
    appId: '1:949650895557:android:ac5494f71f7a4207deb6ac',
    messagingSenderId: '949650895557',
    projectId: 'fir-cli-demo-6be41',
    storageBucket: 'fir-cli-demo-6be41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPvuA4vvbEkGEbLhyipoLhQcdQn9dnsiw',
    appId: '1:949650895557:ios:158961949e237eb5deb6ac',
    messagingSenderId: '949650895557',
    projectId: 'fir-cli-demo-6be41',
    storageBucket: 'fir-cli-demo-6be41.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPvuA4vvbEkGEbLhyipoLhQcdQn9dnsiw',
    appId: '1:949650895557:ios:ec34221c4767f5cadeb6ac',
    messagingSenderId: '949650895557',
    projectId: 'fir-cli-demo-6be41',
    storageBucket: 'fir-cli-demo-6be41.appspot.com',
    iosBundleId: 'com.example.firebaseDemo.RunnerTests',
  );
}
